---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claimdb
  namespace: parasol-demo
  labels:
    app: parasol-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
