kind: Secret
apiVersion: v1
metadata:
  name: claimdb
  namespace: parasol-demo
  labels:
    app: parasol-demo
stringData:
  database-name: claimdb
  database-password: claimdb
  database-user: claimdb
type: Opaque