---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vectordb-milvus
  namespace: parasol-demo-milvus
  labels:
    app: ic-shared-milvus
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
    app.kubernetes.io/version: "2.4.0"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi