---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-etcd-headless
  namespace: parasol-demo-milvus
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "client"
      port: 2379
      targetPort: client
    - name: "peer"
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-etcd
  namespace: parasol-demo-milvus
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
spec:
  type: ClusterIP
  ports:
    - name: "client"
      port: 2379
      targetPort: client
    - name: "peer"
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: vectordb
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-milvus
  namespace: parasol-demo-milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
    app.kubernetes.io/version: "2.4.0"
    component: "standalone"
spec:
  type: ClusterIP
  ports:
    - name: milvus
      port: 19530
      protocol: TCP
      targetPort: milvus
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
  selector:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: vectordb
    component: "standalone"