---
apiVersion: v1
kind: Service
metadata:
  name: milvus-backup
  namespace: parasol-demo-milvus
  labels:
    app.kubernetes.io/name: milvus-backup
spec:
  type: ClusterIP
  ports:
    - name: milvus-backup
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: milvus-backup
    component: milvus-backup
