---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: qwen
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen
  namespace: parasol-demo-llms
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name=qwen2.5'
        - '--max-model-len=2048'
        - '--tensor-parallel-size=1'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 6Gi
        requests:
          cpu: '4'
          memory: 5Gi
      runtime: vllm-cpu
      storageUri: oci://quay.io/rh-aiservices-bu/qwen2.5-0.5b-quantized.w8a8-modelcar:0.0.1
